language: node_js
services:
  - mongodb
node_js:
  - "0.12"
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
env:
  - TRAVIS=true
